/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_fxzjshm_test_Draw */

#ifndef _Included_com_github_fxzjshm_test_Draw
#define _Included_com_github_fxzjshm_test_Draw
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_fxzjshm_test_Draw_DEBUG
#define com_github_fxzjshm_test_Draw_DEBUG 0L
#undef com_github_fxzjshm_test_Draw_DEFAULT_WIDTH
#define com_github_fxzjshm_test_Draw_DEFAULT_WIDTH 100L
#undef com_github_fxzjshm_test_Draw_DEFAULT_HEIGHT
#define com_github_fxzjshm_test_Draw_DEFAULT_HEIGHT 100L
#undef com_github_fxzjshm_test_Draw_PERLIN_YWRAPB
#define com_github_fxzjshm_test_Draw_PERLIN_YWRAPB 4L
#undef com_github_fxzjshm_test_Draw_PERLIN_YWRAP
#define com_github_fxzjshm_test_Draw_PERLIN_YWRAP 16L
#undef com_github_fxzjshm_test_Draw_PERLIN_ZWRAPB
#define com_github_fxzjshm_test_Draw_PERLIN_ZWRAPB 8L
#undef com_github_fxzjshm_test_Draw_PERLIN_ZWRAP
#define com_github_fxzjshm_test_Draw_PERLIN_ZWRAP 256L
#undef com_github_fxzjshm_test_Draw_PERLIN_SIZE
#define com_github_fxzjshm_test_Draw_PERLIN_SIZE 4095L
/*
 * Class:     com_github_fxzjshm_test_Draw
 * Method:    x
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_fxzjshm_test_Draw_x
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_github_fxzjshm_test_Draw
 * Method:    y
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_fxzjshm_test_Draw_y
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
