#!/bin/bash
# javac Case4.java
JAVA_OPTS="-Djava.rmi.server.hostname=192.168.1.152  -Dcom.sun.management.jmxremote.port=8088  -Dcom.sun.management.jmxremote.ssl=false  -Dcom.sun.management.jmxremote.authenticate=false" java Case4
